### ISSUE TITLE
Trying to Build MotionPlus on Pi Bookworm

### ISSUE THREAD

**Issue by Schattenruf** [Motion-Project/motion-packaging#21] opened 2023-10-19 11:39 UTC
Hi there,

as described in the title I am trying to build motionplus on RPi bookwork with the provided guides. But the script does not 100% run through:

```
Usage:    buildplus.sh name email <optional branch>
Name:     Name to use for deb package must not include spaces
Email:    Email address to use for deb package
Branch:   The git branch name of MotionPlus to build (If none specified, uses ma                                                                                                                                                  ster)
Install:  Install required packages
Arch:     Architecture


Using Username: AdhocBuild, User Email: AdhocBuild@nowhere.com, Git Branch: mast                                                                                                                                                  er, Install Pkgs: N, Arch: armv7l, PKGARCH: armhf

All packages installed
Cloning into 'motionplus'...
remote: Enumerating objects: 4303, done.
remote: Counting objects: 100% (1538/1538), done.
remote: Compressing objects: 100% (401/401), done.
remote: Total 4303 (delta 1180), reused 1443 (delta 1129), pack-reused 2765
Receiving objects: 100% (4303/4303), 3.25 MiB | 5.30 MiB/s, done.
Resolving deltas: 100% (3419/3419), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
Cloning into 'motion-packaging'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 253 (delta 86), reused 91 (delta 43), pack-reused 113
Receiving objects: 100% (253/253), 128.81 KiB | 3.07 MiB/s, done.
Resolving deltas: 100% (118/118), done.
rm '.github/ISSUE_TEMPLATE/config.yml'
rm '.github/ISSUE_TEMPLATE/issue.yml'
Version: 0.1.1-git-20231013-a332052
Building package....
Build Error.  Check build log
saved in /home/pi
pi@raspmatic:~ $ vi pi_bookworm_motionplus_0.1.1-git-20231013-a332052
pi_bookworm_motionplus_0.1.1-git-20231013-a332052-1.debian.tar.xz      pi_bookworm_motionplus_0.1.1-git-20231013-a332052-buildlog-armv7l.txt
pi_bookworm_motionplus_0.1.1-git-20231013-a332052-1.dsc                pi_bookworm_motionplus_0.1.1-git-20231013-a332052.orig.tar.gz
pi@raspmatic:~ $ vi pi_bookworm_motionplus_0.1.1-git-20231013-a332052-
pi_bookworm_motionplus_0.1.1-git-20231013-a332052-1.debian.tar.xz      pi_bookworm_motionplus_0.1.1-git-20231013-a332052-1.dsc                pi_bookworm_motionplus_0.1.1-git-20231013-a332052-buildlog-armv7l.txt
pi@raspmatic:~ $ vi pi_bookworm_motionplus_0.1.1-git-20231013-a332052-
pi_bookworm_motionplus_0.1.1-git-20231013-a332052-1.debian.tar.xz      pi_bookworm_motionplus_0.1.1-git-20231013-a332052-1.dsc                pi_bookworm_motionplus_0.1.1-git-20231013-a332052-buildlog-armv7l.txt
pi@raspmatic:~ $ vi pi_bookworm_motionplus_0.1.1-git-20231013-a332052-buildlog-armv7l.txt
make[1]: Entering directory '/tmp/motionplus.4oShEv/motionplus'
make  all-recursive
make[2]: Entering directory '/tmp/motionplus.4oShEv/motionplus'
Making all in src
make[3]: Entering directory '/tmp/motionplus.4oShEv/motionplus/src'
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o alg.o alg.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o alg_sec.o alg_sec.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o conf.o conf.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o dbse.o dbse.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o draw.o draw.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o event.o event.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o exif.o exif.cpp
In file included from /usr/include/c++/12/vector:70,
                 from motionplus.hpp:52,
                 from alg_sec.cpp:20:
/usr/include/c++/12/bits/vector.tcc: In member function ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(iterator, _Args&& ...) [with _Args = {const double&}; _Tp = double; _Alloc = std::allocator<double>]’:
/usr/include/c++/12/bits/vector.tcc:439:7: note: parameter passing for argument of type ‘std::vector<double, std::allocator<double> >::iterator’ changed in GCC 7.1
  439 |       vector<_Tp, _Alloc>::
      |       ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12/vector:64:
In member function ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = double; _Alloc = std::allocator<double>]’,
    inlined from ‘void algsec_image_label(ctx_dev*, cv::Mat&, std::vector<cv::Rect_<int> >&, std::vector<double, std::allocator<double> >&)’ at alg_sec.cpp:116:39:
/usr/include/c++/12/bits/stl_vector.h:1287:28: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >’ changed in GCC 7.1
 1287 |           _M_realloc_insert(end(), __x);
      |           ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o jpegutils.o jpegutils.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o libcam.o libcam.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o logger.o logger.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/etc/motionplus\" -DLOCALEDIR=\"/usr/share/locale\" -Wdate-time -D_FORTIFY_SOURCE=2 -D_THREAD_SAFE    -I/usr/include/p11-kit-1   -I/usr/local/include/libcamera  -I/usr/include/arm-linux-gnueabihf  -I/usr/include/opencv4  -I/usr/include/mariadb/  -I/usr/include/postgresql   -D_REENTRANT     -g -O2 -ffile-prefix-map=/tmp/motionplus.4oShEv/motionplus=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++17 -c -o motionplus.o motionplus.cpp
libcam.cpp: In member function ‘void cls_libcam::cam_config_control_item(char*, char*)’:
libcam.cpp:424:39: error: ‘SceneFlicker’ is not a member of ‘libcamera::controls::draft’
  424 |         controls.set(controls::draft::SceneFlicker, atoi(pvalue));
      |                                       ^~~~~~~~~~~~
make[3]: *** [Makefile:503: libcam.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/tmp/motionplus.4oShEv/motionplus/src'
make[2]: *** [Makefile:568: all-recursive] Error 1
make[2]: Leaving directory '/tmp/motionplus.4oShEv/motionplus'
make[1]: *** [Makefile:412: all] Error 2
make[1]: Leaving directory '/tmp/motionplus.4oShEv/motionplus'
dh_auto_build: error: make -j4 returned exit code 2
make: *** [debian/rules:10: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

Same happens to me on the manual installation way. I do not know where this "SceneFlicker" comes from or if I am missing a package.

Could you help me out?

Thank you :)

**Comment by Mr-Dave** [comment] 2023-10-20 22:57
There was a revision to libcamera upstream.  A revision will be pushed to the Motionplus branch shortly.  Duplicate of [issue 103](https://github.com/Motion-Project/motionplus/issues/103)

**Closed as completed by Mr-Dave** 2023-10-20 22:57 UTC
