### ISSUE TITLE
postinst starts motion.service but /var/log/motion is missing

### ISSUE THREAD

**Issue by MichaIng** [Motion-Project/motion-packaging#15] opened 2022-03-18 15:51 UTC
Currently installing the `motion` package causes an error since its `postinst` script tries to start `motion.service`, which is doomed to fail as the default log directory `/var/log/motion` does not exist yet.

There are multiple options to resolve this:
- Configure debhelper to not add the service start block. It does this automatically if a systemd service file exits, but I guess there is a way to suppress this.
- Pre-create and chown `/var/log/motion` via `postinst` before the debhelper block.
- Pre-create `/var/log/motion` via service:
    - Legacy compatible way:
        ```
        ExecStartPre=!/bin/mkdir -p /var/log/motion
        ExecStartPre=!/bin/chown motion:adm /var/log/motion
        ```
    - Modern way, requires systemd v235 or later:
        ```
        LogsDirectory=motion
        ```

**Comment by Mr-Dave** [comment] 2022-07-03 23:13
closed via 0da97213aa8ff7fc1b758e2dbeea80ca43c5ad0c

**Closed as completed by Mr-Dave** 2022-07-03 23:13 UTC

**Comment by Mr-Dave** [comment] 2022-07-06 02:36
Another commit c0889f0498cb7cb37c02425a4602343ff96128d4 has been pushed to resolve this.  (hopefully correctly this time)

I would also note that this will only address the packages created by Motion-Project.  Packages created by Debian (and other variants) will continue to have this issue.  The issue is logged in the Debian system [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=988661)

**Comment by MichaIng** [comment] 2022-07-07 21:31
@Mr-Dave 
Jep, better solution for now since it supports older distro versions as well.
